### ISSUE TITLE
cannot get stringinject on send() to work

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#265]
@jjr840430 I cannot get stringinject on send() to work on macOS, is there something wrong with my config or usage?

```
$ cat send.conf 
stringinject,INJECT_FORMAT_STR,send,4:4,1
```

my sample send.c:
```
$ cat ~/tmp/send.c
#include <sys/socket.h>
#include <arpa/inet.h>

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
 
int
main()
{
	int sock;
	struct sockaddr_in server;
	char message[1000]="testtesttest";
	sock = socket(AF_INET, SOCK_STREAM , 0);
	if (sock == -1) {
        	printf("Could not create socket");
		exit(1);
	}
	printf("socket created\n");
	/* google.com */     
	server.sin_addr.s_addr = inet_addr("172.217.24.36");
	server.sin_family = AF_INET;
	server.sin_port = htons(80);
	if (connect(sock, (struct sockaddr *)&server, sizeof(server)) < 0) {
		printf("connect failed\n");
		exit(1);
	}
	printf("connected\n");
	if (send(sock, message , strlen(message), 0) < 0) {
		printf("send failed\n");
		return 1;
	}
	printf("sent\n");
	close(sock);
	return(0);
}
```

my run:
```
$ ./retrace -f send.conf ~/tmp/send
<SNIP>
(4515) memcpy(0x7fff4c000000, 0x10391af8e, 10, ) = 0x7fff4c000000
connected
(4515) free(0x0, )
(4515) printf("connected\n" -> "connected\n", ) = 10
(4515) strlen("testtesttest", ) = 12
(4515) sendto(0 [connected[172.217.24.36:80]], 0x7fff5c2e5320, 12, 0xc00000000, 0, ) = 12
	0000000	 7465 7374 7465 7374 7465 7374                     | testtesttest
(4515) send(0 [connected[172.217.24.36:80]], 0x7fff5c2e5320, 12, ) = 12
	0000000	 7465 7374 7465 7374 7465 7374                     | testtesttest
(4515) memcpy(0x7fff4c000000, 0x10391afa6, 5, ) = 0x7fff4c000000
sent
(4515) free(0x0, )
(4515) printf("sent\n" -> "sent\n", ) = 5
(4515) close(0 [connected[172.217.24.36:80]], ) = 0
(4515) exit(0, )
(4515) fwrite(0x7fff5c2e55b8, 1, 0, 0x7fffc59241a8 [fd 1], ) = 0
(4515) fwrite(0x7fff5c2e55b8, 1, 0, 0x7fffc59241a8 [fd 1], ) = 0
(4515) fwrite(0x7fff5c2e55b8, 1, 0, 0x7fffc5924240 [fd 2], ) = 0
(4515) fwrite(0x7fff5c2e55b8, 1, 0, 0x7fffc5924240 [fd 2], ) = 0
(4515) _exit(0, )
```

**Comment by jjr840430** [comment]
@erikbor It's working on Ubuntu, Let me check on MacOS.

**Comment by jjr840430** [comment]
@erikbor It's really not working on MacOS :(

**Comment by jjr840430** [comment]
@erikbor rtr_get_multiple_config() function  doesn't work on MacOS, so it couldn't get configuration for fuzzing send() function.
I will look that function.
@drystone Can you help me to check why rtr_get_multiple_config() isn't working?

**Comment by drystone** [comment]
@jjr840430 @erikbor there was a string termination bug in get_config() which could be the cause. I've pushed a fix so please try again.

**Comment by erikbor** [comment]
@drystone @jjr840430 I pulled the latest code and built it but it still doesn't work on macOS. I also tried ```INJECT_BUF_OVERFLOW```:

```sh
$ ./retrace -f ~/tmp/send.conf ~/tmp/send
<SNIP>
connected
(17505) free(0x0, )
(17505) printf("connected\n" -> "connected\n", ) = 10
(17505) strlen("testtesttest", ) = 12
(17505) sendto(0 [connected[172.217.24.36:80]], 0x7fff54d42300, 12, 0xc00000000, 0, ) = 12
	0000000	 7465 7374 7465 7374 7465 7374                     | testtesttest
(17505) send(0 [connected[172.217.24.36:80]], 0x7fff54d42300, 12, ) = 12
	0000000	 7465 7374 7465 7374 7465 7374                     | testtesttest
(17505) memcpy(0x7fff4c000000, 0x10aebdfa6, 5, ) = 0x7fff4c000000
sent
(17505) free(0x0, )
(17505) printf("sent\n" -> "sent\n", ) = 5
(17505) close(0 [connected[172.217.24.36:80]], ) = 0
(17505) exit(0, )
(17505) fwrite(0x7fff54d42598, 1, 0, 0x7fffc59241a8 [fd 1], ) = 0
(17505) fwrite(0x7fff54d42598, 1, 0, 0x7fffc59241a8 [fd 1], ) = 0
(17505) fwrite(0x7fff54d42598, 1, 0, 0x7fffc5924240 [fd 2], ) = 0
(17505) fwrite(0x7fff54d42598, 1, 0, 0x7fffc5924240 [fd 2], ) = 0
(17505) _exit(0, )
$ cat ~/tmp/send.conf 
stringinject,INJECT_BUF_OVERFLOW,send,4:4,1
```

**Comment by jjr840430** [comment]
@erikbor sorry for delay, I didn't still find the bug in config parser part.
will update soon.
Also is it possible to support remote access to Mac VM? @drystone doesn't have mac os.

**Comment by erikbor** [comment]
@jjr840430 I don't use VMs only physical hardware and I can't provide remote access at this moment for that reason :(

**Comment by jjr840430** [comment]
Fixed on #284
